### ISSUE TITLE
Add an option to skip notifications for "pre-release"

### ISSUE THREAD

**Issue by crazy-max** [vfeskov/gitpunch#53]
Hi,

Today we receive notifications for `pre-release` : https://github.com/brave/browser-laptop/releases/tag/v0.25.203

![image](https://user-images.githubusercontent.com/1951866/47682414-96865f00-dbcc-11e8-9d7b-1575c211f63a.png)

Is it possible to add an option to skip notifications for these ?

**Comment by Jacalz** [comment]
+1 on that 👍 Especially with Brave 😅

**Comment by vfeskov** [comment]
im basically done with this feature, you'll be able to subscribe to major & minor releases only, meaning any release that matches pattern `*.*.0`

i want to properly cover all the usecases with end-to-end tests before i deploy it, which will take some time, probably this week i'll finish

**Comment by crazy-max** [comment]
Awesome @vfeskov ! Thanks a lot

**Comment by vfeskov** [comment]
done, will describe in release notes

**Comment by crazy-max** [comment]
Hi @vfeskov, unfortunately this implementation did not solved my issue. Like I said, I was thinking to check the release status (draft, pre-release, release) :

![image](https://user-images.githubusercontent.com/1951866/48251391-c241ea00-e401-11e8-8225-01008d01a3f6.png)

Where :

* `release = !release.draft && !release.prerelease`
* `prerelease = release.prerelease`
* `draft = release.draft`

**Comment by vfeskov** [comment]
thing is im not using github api because of rate limiting, im using atom feeds, e.g., https://github.com/angular/angular/releases.atom , and i think it doesn't have those flags, does it?

**Comment by crazy-max** [comment]
Ok legit, I understand the limitation. And unfortunalety, you right [there is no evidence for these flags](https://github.com/isaacs/github/issues/410) in ATOM feeds :persevere:
